Made cold brew coffee recipe
LukeSmithxyz/based.cooking pull request #288
Opened 2021-03-20 18:09 UTC by actuallyexeon

2021-03-20 21:17 UTC, Morelcia commented
Missing .md extension

2021-03-21 00:51 UTC, hallzy commented on src/cold-brew-coffee
> +- 1/2 or 1 tbsp | Optional
1/2 or 1 tbsp of what?

2021-03-22 00:56 UTC, actuallyexeon commented on src/cold-brew-coffee
> +- 1/2 or 1 tbsp | Optional
Oop, I meant sugar

2021-03-22 01:39 UTC, hallzy commented on src/cold-brew-coffee
> +- 1/2 or 1 tbsp | Optional
```suggestion
- 1/2 or 1 tbsp of sugar | Optional
```

2021-03-22 15:15 UTC, Knarkzel approved these changes

2021-03-22 15:17 UTC, DGKSK8LIFE approved these changes

2021-03-22 16:01 UTC, hallzy requested changes
btw, looks like `sugar` hasn't been added to the ingredients list as mentioned above

2021-03-23 14:04 UTC, Holsterbau commented
Is this really cold brewing coffee? To my understanding, [cold brewing](https://en.wikipedia.org/wiki/List_of_coffee_drinks#Cold_brew) is a specific term for a process of brewing coffee through cold extraction, as opposed through the much more common hot brewing process. A notable advantage of cold brewing is that the resulting brew has almost no acidity, unlike hot brewed coffee. This just looks like a [regular frappé](https://en.wikipedia.org/wiki/List_of_coffee_drinks#Iced).

2021-03-25 19:12 UTC, actuallyexeon commented
Well most people call it a Cold Brew AFAIK

2021-03-25 19:28 UTC, Holsterbau commented
I am just speaking from the perspective that if someone wishes to make `cold-brew-coffee.md` in the future about how to cold brew coffee, this recipe would take up the spot even though it isn't *really* cold brewed coffee. It should probably be renamed to `iced-coffee.md` or something of the kind.

2021-03-26 22:00 UTC, actuallyexeon commented
Ok! I'll rename it then

2021-03-26 23:02 UTC, DGKSK8LIFE approved these changes
Ok good definition change if everyone's in agreeance with this.

2022-06-29 14:18 UTC, closed without merging