Create crepes.md
LukeSmithxyz/based.cooking pull request #395
Opened 2021-03-21 22:13 UTC by ZeikoFr

Hi, added a classic french recipe for breakfast and dessert. Hope you like it !

2021-03-21 22:16 UTC, m-chrzan commented
There already is a [French crepes](https://based.cooking/french-crepes) recipe. Does this one differ significantly?

2021-03-21 22:22 UTC, hallzy commented on src/crepes.md
> +- 💤 Rest time: up to 24 hours for a better taste but can be done immediatly after prep
```suggestion
- 💤 Rest time: up to 24 hours for a better taste but can be done immediately after prep
```

2021-03-21 22:23 UTC, hallzy commented on src/crepes.md
> +- a bit of salt
```suggestion
```

No need for salt/pepper in ingredients list per the contribution instructions

2021-03-21 22:24 UTC, hallzy commented on src/crepes.md
> +10. Once the other side id cooked put the crepe on a plate and start another one (adjust the quantity of batter if necessary.
```suggestion
10. Once the other side is cooked put the crepe on a plate and start another one (adjust the quantity of batter if necessary.
```

2021-03-21 22:26 UTC, hallzy commented on src/crepes.md
> +;tags: dessert breakfast french
```suggestion

;tags: dessert breakfast french
```

No need for the contribution heading if you aren't putting your name in.

2021-03-21 22:27 UTC, hallzy commented on src/crepes.md
> +# Crèpes
```suggestion
# Crêpes
```

2021-03-21 22:29 UTC, hallzy requested changes
See suggested changes.

Also, as pointed out by another user, there is a Crêpe recipe already, so unless there is a significant difference, I don't know if this will be merged.

Maybe a better option would be to update the original if you think it is lacking in some way.

2021-03-22 12:25 UTC, ZeikoFr commented
Yeah I didn't see the first recipe I close the PR and will update the original one

2021-03-22 12:25 UTC, closed without merging