Homemade Ice Cream Recipe
LukeSmithxyz/based.cooking pull request #437
Opened 2021-03-23 14:30 UTC by Socerest2

- Homemade Ice Cream

2021-03-23 14:44 UTC, DGKSK8LIFE approved these changes

2021-03-23 16:21 UTC, hallzy requested changes
Is there an image that you can upload for this recipe?

2021-03-23 16:21 UTC, hallzy commented on src/homemade-ice-cream.md
> +- A Mason jar or some equivilent
```suggestion
- A Mason jar or some equivalent
```

2021-03-23 16:21 UTC, hallzy commented on src/homemade-ice-cream.md
> +- A small pinch of salt
Salt/Pepper shouldn't be listed as ingredients.

I also noticed that it isn't listed in the directions. If there is a specific place that salt should be added, you can mention it in the directions, but no need for it in ingredients.

2021-03-23 16:21 UTC, hallzy commented on src/homemade-ice-cream.md
> +;tags: dessert american
```suggestion
4. You are done! Now put your jar in your freezer for at least 2 hours, I put mine in for 4 hours. (Remember longer is better!)

## Contribution

- Vince - [website](https://vincestuff.com), [github](https://github.com/Socerest2)

;tags: dessert american
```

Add some extra new lines between, for better separation.

2021-03-23 16:26 UTC, Socerest2 commented
> Is there an image that you can upload for this recipe?

Not at the moment since I ran out of heavy cream.

2021-03-23 16:32 UTC, hallzy approved these changes

2021-03-23 17:43 UTC, Knarkzel commented
This is a very sugary recipe indeed...

2021-03-27 01:40 UTC, zyansheep approved these changes
wow this looks insanely simple and good. any pics?

2021-03-28 18:04 UTC, Socerest2 commented
> wow this looks insanely simple and good. any pics?

Thanks! Sadly not yet, but soon, hopefully!

2021-06-01 02:57 UTC, Socerest2 commented
Any possibility of this being added?

2021-06-01 14:45 UTC, zyansheep commented
> Any possibility of this being added?

@LukeSmithxyz What do you think?

2021-06-01 16:09 UTC, DGKSK8LIFE commented
> > Any possibility of this being added?
> 
> @LukeSmithxyz What do you think?

He's too busy grilling to merge our PRs atm.

2022-04-19 22:56 UTC, Socerest2 commented
Too much grillin - No Ice Cream

2022-06-29 14:18 UTC, closed without merging