Updated lasagna recipe
LukeSmithxyz/based.cooking pull request #459
Opened 2021-03-23 22:21 UTC by yiusa

expanded the existing lasagna recipe

2021-03-23 22:37 UTC, Socerest2 requested changes
Just a small bit of grammar fixes

2021-03-23 22:37 UTC, Socerest2 commented on src/ricotta-lasagna-filling.md
> +- oregano (optional)
```suggestion
- Oregano (Optional)
```
- Minor Grammar Fix

2021-03-23 22:37 UTC, Socerest2 commented on src/ricotta-lasagna-filling.md
> +1. mix the ricotta cheese together with a handfull of finely grated parmesan.
```suggestion
1. Mix the ricotta cheese together with a handfull of finely grated parmesan.
```

2021-03-23 22:37 UTC, Socerest2 commented on src/ricotta-lasagna-filling.md
> +2. add the oregano and the egg and mix.
```suggestion
2. Add the oregano and the egg and mix.
```

2021-03-23 22:37 UTC, Socerest2 commented on src/lasagna.md
> +10. once it is done cooking take it out of the oven and cover again with aluminum foil, let it rest for 10 minutes before serving.
```suggestion
10. Once it is done cooking take it out of the oven and cover again with aluminum foil, let it rest for 10 minutes before serving.
```

2021-03-23 22:40 UTC, yiusa commented
> Just a small bit of grammar fixes

thanks for the check should be fixed.

2021-03-23 22:41 UTC, Socerest2 approved these changes
Looks Good!

2021-03-23 23:20 UTC, hallzy approved these changes

2021-03-24 00:17 UTC, LukeSmithxyz commented
Get rid of the meat tag.

2021-03-24 00:31 UTC, LukeSmithxyz commented
There's also no reason this needs to be named "Fresh" Lasagna.

2021-03-24 00:49 UTC, Socerest2 requested changes
Github glitch it got posted twice. Anyways. heres some stuff to fix based on lukes comments.

2021-03-24 00:49 UTC, Socerest2 commented on src/lasagna.md
> +![fresh-lasagna](pix/fresh-lasagna.webp)
```suggestion
![Lasagna](pix/fresh-lasagna.webp)
```
Lukes Stuff

2021-03-24 00:49 UTC, Socerest2 commented on src/lasagna.md
> +# Fresh lasagna
```suggestion
# Lasagna
```
Per Luke Request

2021-03-24 00:49 UTC, Socerest2 commented on src/lasagna.md
> +;tags: italian pasta meat
```suggestion
;tags: italian pasta
```

2021-03-24 08:22 UTC, printplaatreparatie commented on src/lasagna.md
> +- [fresh Bolognese sauce](bechamel-sauce.html) or about 1 litre worth of store-bought sauce
```suggestion
- [Fresh Bolognese sauce](bolognese-sauce.html) or about 1 litre worth of store-bought sauce
```

2021-03-24 08:59 UTC, yiusa commented
Alright, fixed the recipes like you guys suggested. Should be all good now. Thanks Socerest2 and printplaatreparatie for the 
proofreading.

2021-03-24 13:51 UTC, LukeSmithxyz commented
The image name should match the markdown filename (no fresh).

2021-03-24 15:12 UTC, yiusa commented
> The image name should match the markdown filename (no fresh).

Alright i think all should be like it's supposed to be now, ill be more careful when proofreading  my recipes before creating pull requests in the future so that this doesn't happen again.

2021-03-25 01:05 UTC, merged