Add Apple Crostata Recipe
LukeSmithxyz/based.cooking pull request #499
Opened 2021-03-26 03:17 UTC by zyansheep

Found this on reddit, it looked really good...

2021-03-26 03:21 UTC, zyansheep commented
why is the image limit 150k? It should be around 500kb because high-def images are cool.

2021-03-26 04:09 UTC, hallzy requested changes
I hate to be 'that' guy, but can you shrink your image by at least 1062 bytes to make the CI script happy. :)

The original readme from Luke actually mentions less than 100kB so the 150 is being pretty generous relatively speaking

2021-03-26 04:09 UTC, hallzy commented on src/apple-crostata.md
> +4. Bake in the oven at 425° F (215 °C) for 40 min.
```suggestion
4. Bake in the oven at 425°F (215°C) for 40 min.
```

2021-03-26 15:47 UTC, zyansheep commented
alright... I'll ffmpegify it. I committed it previously as it was because a lot of the existing images were way over 150kb

2021-03-26 15:52 UTC, hallzy approved these changes
Thanks :D

2021-03-27 01:20 UTC, zyansheep commented on src/apple-crostata.md
> +- 3-4 Apples
```suggestion
- 3-4 Peeled Apples
```
specify to use peeled apples

2022-06-29 14:18 UTC, closed without merging