Add recipe for polish bigos
LukeSmithxyz/based.cooking pull request #503
Opened 2021-03-26 11:30 UTC by kKondratek

2021-03-26 15:39 UTC, printplaatreparatie commented
I love this recipe! I'm not from Poland, but for me are tomato paste and garlic essential for the good taste. @kKondratek what do you think?

2021-03-26 15:55 UTC, hallzy requested changes

2021-03-26 15:55 UTC, hallzy commented on src/polish-bigos.md
> +3. Pour one and half glasses of warm water with salt and pepper (not to much salt!).
```suggestion
3. Pour one and half glasses of warm water with salt and pepper (not too much salt!).
```

2021-03-26 18:22 UTC, kKondratek commented
> I love this recipe! I'm not from Poland, but for me are tomato paste and garlic essential for the good taste. @kKondratek what do you think?

I heard about this variation :) never tried before but I'm sure it's great too

2021-03-26 19:13 UTC, DGKSK8LIFE approved these changes

2021-04-04 07:06 UTC, m-chrzan commented
I would simplify the name to just "bigos".

2021-04-04 13:00 UTC, kKondratek commented
> I would simplify the name to just "bigos".
@m-chrzan I agree, just renamed it

2021-04-04 17:29 UTC, hallzy approved these changes

2022-06-29 14:18 UTC, closed without merging