Add search feature
LukeSmithxyz/based.cooking pull request #533
Opened 2021-04-01 04:44 UTC by omar2205

Adds search feature to the home page
![image](https://user-images.githubusercontent.com/1373867/113244610-a29f0b00-92b5-11eb-9996-f1324adbdb24.png)

2021-04-01 04:45 UTC, omar2205 commented
The smallest amount of JS to search from recipes list

2021-04-01 05:15 UTC, hallzy commented
Short of not having the variables, this is probably the shortest way to do it, and doesn't require continuously removing and adding DOM elements.

```javascript
const rec = document.querySelectorAll('#artlist li')
const search = document.querySelector('#search')

search.addEventListener('change', e => {
    const searchText = e.target.value.toLowerCase();

    rec.forEach(el => {
        const recipeName = el.innerText.toLowerCase();
        const isMatch = recipeName.indexOf(searchText) > -1;

        el.hidden = !isMatch;
    });
});
```

That being said, I will be shocked if this gets into the project.

This search is no different to a standard ctrl+f search, and every issue I have seen created about adding any javascript at all has been closed.

one ref: #150

2021-04-01 05:25 UTC, omar2205 commented
yes there is the CTRL+F, but to type & search is just easier

2021-04-01 23:31 UTC, omar2205 commented
![image](https://user-images.githubusercontent.com/1373867/113364163-16432580-9353-11eb-8640-e1477e0142b3.png)

2021-04-02 15:17 UTC, LukeSmithxyz commented
I am open to this. I will test it out when I can.

2021-04-02 15:25 UTC, LukeSmithxyz commented
To be clear, yes, search via ctrl-f is possible, but this avoids the issue of visual overwhelm. Users can see all "pasta" entries in one place, rather than ctrl-fing time after time again to different parts of the doc.

Important to me is it maintaining perfect compatibility with cli access.

2021-04-02 15:52 UTC, DGKSK8LIFE commented
So you are ok with contributing Javascript to this repo now? @LukeSmithxyz Hmm .

2021-04-02 16:24 UTC, hallzy requested changes
If this is something we are going to add, then this is my review. The search does not work for me.

The script is executed before the recipe list is rendered, so the script doesn't know about any recipes.

We will either have:

- Move this into the footer file
- wrap the script in an onload or something, or
- take the script out and put it into a separate `.js` file, and reference it with `<script defer ...>` in this file in the head.

2021-04-02 16:35 UTC, hallzy requested changes

2021-04-02 16:35 UTC, hallzy commented on templates/article_list_header.html
> +})
```suggestion
window.addEventListener('load', () => {
  const rec = document.querySelectorAll('#artlist li');
  const search = document.querySelector('#search');
  const clearSearch = document.querySelector('.clear-search');

  search.addEventListener('change', e => {
    // grab search input value
    const searchText = e.target.value.toLowerCase();
    // for each receipe hide all but matched
    rec.forEach(el => {
      const recipeName = el.innerText.toLowerCase();
      const isMatch = recipeName.includes(searchText);

      el.hidden = !isMatch;
    });
  });

  clearSearch.addEventListener('click', e => {
    search.value = '';
    rec.forEach(el => el.hidden = false);
  });
});
```

This for example, would work.

2021-04-03 00:51 UTC, hallzy approved these changes

2022-05-26 21:26 UTC, closed without merging