Adding recipe for aioli/mayo and burger dressing with pictures
LukeSmithxyz/based.cooking pull request #542
Opened 2021-04-03 10:56 UTC by kristianbrox

2021-04-03 18:01 UTC, hallzy requested changes

2021-04-03 18:01 UTC, hallzy commented on src/mayonnaise-or-aioli.md
> +;tags: mayonnaise aioli
```suggestion
;tags: sauce basic aioli
```
Again, sauce and basic would probably be good here. Mayo is a bit generic as a tag I think.

2021-04-03 18:11 UTC, hallzy approved these changes

2021-04-06 12:56 UTC, merged

2021-04-07 09:58 UTC, Danoloan10 commented
The title of this recipe is misleading.

Aioli is not "mayonaisse with garlic". It does the trick, but true aioli is made with only olive oil, garlic and salt; no eggs. Adding garlic to mayonaisse is garlic mayonaisse.

2021-04-07 14:30 UTC, kristianbrox commented
@Danoloan10 I'm aware of this view of aioli. Today most recepies in most places uses eggs in aioli, although I do agree that the original aioli does not contain eggs nor added acid. Feel free to add a recipe called "authentic/real aioli" or something if you find and master a recipe 👍 I have never tried this, but would like to taste it. 

I am also open to change the text in the recipe a bit to state that it is not traditional aioli.