Add Yibin Burning Noodles Recipe
LukeSmithxyz/based.cooking pull request #558
Opened 2021-04-07 13:05 UTC by ThePademelon

This is a recipe I saw on [YouTube](https://www.youtube.com/watch?v=A1y-OhS9z20) and also read about on [The Mala Market](https://blog.themalamarket.com/yibin-ran-mian-burning-noodles-from-yibin-sichuan/). I've simplified, standardised and consolidated the recipe for this project.

2021-04-07 16:06 UTC, hallzy requested changes

2021-04-07 16:06 UTC, hallzy commented on src/yibin-burning-noodles.md
> +8. Stir thouroughly.
```suggestion
8. Stir thoroughly.
```

2021-04-13 02:38 UTC, ThePademelon commented on src/yibin-burning-noodles.md
> +10. Stir thouroughly.
```suggestion
10. Stir thoroughly.
```

2021-04-13 02:43 UTC, hallzy approved these changes

2021-04-13 04:04 UTC, DGKSK8LIFE approved these changes

2021-04-15 13:20 UTC, merged