Added baked potato recipe
LukeSmithxyz/based.cooking pull request #570
Opened 2021-04-12 03:04 UTC by teroff

2021-04-12 03:28 UTC, hallzy requested changes

2021-04-12 03:28 UTC, hallzy commented on src/baked-potatoes.md
> +- 6-7 Yukon pototoes (you can use any potatoes you like)
```suggestion
- 6-7 Yukon potatoes (you can use any potatoes you like)
```

2021-04-12 03:28 UTC, hallzy commented on src/baked-potatoes.md
> +- Any seasoning you like
```suggestion
```

Remove salt/pepper and seasonings 'to taste' from ingredients. They can be mentioned below in the directions.

2021-04-12 03:28 UTC, hallzy commented on src/baked-potatoes.md
> +- 1/3 cup of any vegitable oil
```suggestion
- 1/3 cup of any vegetable oil
```

2021-04-12 03:28 UTC, hallzy commented on src/baked-potatoes.md
> +1. Preheat the oven to 425F/220C
```suggestion
1. Preheat the oven to 425°F/220°C
```

2021-04-12 03:28 UTC, hallzy commented on src/baked-potatoes.md
> +3. Put the sliced poptatoes into a bowl
```suggestion
3. Put the sliced potatoes into a bowl
```

2021-04-12 03:28 UTC, hallzy commented on src/baked-potatoes.md
> +2. Wash potatoes and slice into 5mm slices
```suggestion
2. Wash potatoes and cut into into 5mm slices
```

2021-04-12 03:28 UTC, hallzy commented on src/baked-potatoes.md
> +5. Add 1/3 cup of a vegitable oil
```suggestion
5. Add 1/3 cup of a vegetable oil
```

2021-04-12 03:28 UTC, hallzy commented on src/baked-potatoes.md
> +6. Mix everything and put it on the baking pan
```suggestion
6. Mix everything and put it on a baking sheet (optionally lined with baking paper to make cleanup easier) for 20 to 25 minutes.
```

2021-04-12 03:28 UTC, hallzy commented on src/baked-potatoes.md
> +
```suggestion
```

2021-04-12 03:52 UTC, hallzy requested changes

2021-04-12 03:52 UTC, hallzy commented on src/baked-potatoes.md
> +## Contribution
```suggestion
## Contribution
```

Can probably get rid of this since it is in step 7 now.

2021-04-12 05:47 UTC, hallzy approved these changes

2021-04-21 22:53 UTC, siggines requested changes

2021-04-22 17:43 UTC, siggines approved these changes
All good 👌

2021-04-22 19:02 UTC, DGKSK8LIFE approved these changes

2021-05-16 12:52 UTC, AndrewDaGuy approved these changes

2022-06-29 14:20 UTC, closed without merging