challah-bread
LukeSmithxyz/based.cooking pull request #571
Opened 2021-04-12 13:22 UTC by siggines

A kind of braided bread preperation.

2021-04-12 13:28 UTC, siggines commented
First check failed as I put a comma after tag by mistake.

2021-04-12 15:54 UTC, hallzy requested changes

2021-04-12 15:54 UTC, hallzy commented on src/challah-bread.md
> +A kind of braided bread preperation.
```suggestion
A kind of braided bread preparation.
```

2021-04-12 15:54 UTC, hallzy commented on src/challah-bread.md
> +10. Grease two baking trays or use baking paper, cover with dry cloth and let rise for one hour. Preheat oven to 190 C / Gas mark 5.
```suggestion
10. Grease two baking trays or use baking paper, cover with dry cloth and let rise for one hour. Preheat oven to 190°C / Gas mark 5.
```

2021-04-12 15:54 UTC, hallzy commented on src/challah-bread.md
> +http://jacobsiggins.co.uk
```suggestion
- siggines - [website](http://jacobsiggins.co.uk)
```

2021-04-12 19:04 UTC, siggines commented
^ Thanks

2021-04-12 19:16 UTC, hallzy approved these changes

2021-04-13 13:17 UTC, DGKSK8LIFE approved these changes

2021-04-15 13:18 UTC, merged