beef-kidney
LukeSmithxyz/based.cooking pull request #587
Opened 2021-04-18 15:33 UTC by Philip-Wittamore

2021-04-18 16:24 UTC, DGKSK8LIFE requested changes

2021-04-18 16:24 UTC, DGKSK8LIFE commented on src/beef-kidney
> +- fresh parsley
can you quantify how much parsley?

2021-04-18 16:24 UTC, DGKSK8LIFE commented on src/beef-kidney
> +2. cut the kidney into pieces
elaborate on how to cut the kidney

2021-04-18 16:24 UTC, DGKSK8LIFE commented on src/beef-kidney
> +5. fry for 10 minutes while stirring
How to fry it?

2021-04-18 17:16 UTC, hallzy requested changes
In addition to the other comments, please rename your files:

`data/pix/beef-kidney.webP` -> `data/pix/beef-kidney.webp`

`src/beef-kidney` -> `src/beef-kidney.md`

2021-04-18 17:16 UTC, hallzy commented on src/beef-kidney
> +- 60gr butter
```suggestion
- 60g butter 
```

2021-04-18 17:16 UTC, hallzy commented on src/beef-kidney
> +- 400gr croutons or toasted bread in pieces
```suggestion
- 400g croutons or toasted bread in pieces
```

2021-04-18 17:16 UTC, hallzy commented on src/beef-kidney
> +9. add about 400g of toasted bread in pieces
```suggestion
9. Add in the croutons
```

2021-04-19 07:11 UTC, Philip-Wittamore commented on src/beef-kidney
> +- fresh parsley
a sprig of fresh parsley

2021-04-19 12:21 UTC, DGKSK8LIFE approved these changes

2021-04-21 01:50 UTC, merged