Adding new recipe: brownie in a mug
LukeSmithxyz/based.cooking pull request #588
Opened 2021-04-19 15:26 UTC by raxiam

2021-04-19 16:36 UTC, DGKSK8LIFE approved these changes

2021-04-21 14:42 UTC, siggines approved these changes

2021-04-21 14:42 UTC, siggines commented on src/brownie-in-mug.md
> +1. Add the dry ingredients to a regular sized coffee mug, preferable in the order they are listed in (easier to mix).
```suggestion
1. Add the dry ingredients to a regular sized coffee mug, preferably in the order they are listed in (easier to mix).
```

2021-04-21 16:19 UTC, DGKSK8LIFE commented on src/brownie-in-mug.md
> +1. Add the dry ingredients to a regular sized coffee mug, preferable in the order they are listed in (easier to mix).
My bad. didn't catch that

2021-04-21 22:50 UTC, siggines approved these changes

2021-04-26 13:43 UTC, siggines requested changes

2021-04-26 13:43 UTC, siggines commented on src/brownie-in-mug.md
> +;tags: dessert snack basic baking
```suggestion
;tags: dessert snack basic
```
Sorry, didn't catch this. 'Baking' is not a good tag, as most recipes involve baking, and the existing baking tag only has  a couple recipes, and should be removed soon. 
Also this recipe doesn't involve baking lol

2022-06-29 14:20 UTC, closed without merging