Add pasta a la vodka
LukeSmithxyz/based.cooking pull request #660
Opened 2021-07-03 11:21 UTC by engeir

2021-07-29 14:03 UTC, Socerest2 requested changes
It looks really good! In terms of wanting to eat and the recipe in general. I'm a little confused on the `./` in certain parts though.

2021-07-31 14:32 UTC, engeir commented on src/pasta-a-la-vodka.md
> +    add a tsp.\ of sugar; if (3) it is not salty enough, wait until the pasta is in; if
Oh right, that's a bad habbit from writing Latex, where the \ makes a smaller whitespace.

They should be removed like you suggested :)

2021-08-01 19:35 UTC, Socerest2 approved these changes
Looks good!

2021-08-01 20:10 UTC, DGKSK8LIFE approved these changes

2022-06-29 14:15 UTC, closed without merging